# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sciblog
email: airrayagroup@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/sciblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: AIRRAYA

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
paginate: 5
paginate_path: 'page:num/'
comments: true
excerpt_separator: <!-- more -->